### ISSUE TITLE
Question about base tracker`s update using more Precise bbox from Alpha Net

### ISSUE THREAD

**Issue by Cloveryww** [MasterBin-IIAU/AlphaRefine#5]
Hi,
Thanks for your great work! And I have a question after reading your AlphaRefine code.
You use Alpha Net to refine base tracker`s output bbox, but not return the more precise bbox which produced from mask to the base tracker for updating?? Am I correct?? If the performance will greater if the more precise bbox help base tracker updating?

Looking forward to your reply~~

**Comment by MasterBin-IIAU** [comment]
Hi, thanks for your interest in our work. 
Your understanding is right. In this code, we only use AlphaRefine to generate the precise mask, while not affecting the base tracker. The reason is that the box transformed from the mask is not always reliable. In our latest paper (https://arxiv.org/pdf/2012.06815.pdf), we use the box predicted by the corner branch to refine the base tracker's results. And in the next frame, the search region is cropped based on the refined box. we will release the complete code after our paper is accepted.

**Comment by Cloveryww** [comment]
Thanks for your reply！！
